### ISSUE TITLE
Merging a variable-free template adds no metric

### ISSUE THREAD

**Issue by loganmzz** [dmoll1974/targets-io#31]
I have created a template from an existing dashboard in order to export it. So created template has no variable. When merging this template with a blank dashboard, nothing appears in preview and after submitting, there's no metric.

**Comment by dmoll1974** [comment]
Hi Logan,

What I suggest to change is the following:

In the View template view I will display a warning when no variables are configured, saying the template cannot be used / is invalid until a minimum of one variable has been configured.

In the "add metric from template" autocomplete list I will only display valid templates.

Does this make sense to you or do you have some other use case in mind?

Cheers Daniel

**Comment by dmoll1974** [comment]
pushed [commit/eeb60b42af7acad7e78e9d7e430cf5135ce1fc18](https://github.com/dmoll1974/targets-io/commit/eeb60b42af7acad7e78e9d7e430cf5135ce1fc18)

Can you please review?

**Comment by loganmzz** [comment]
I'm wondering if a variable-free template can still be valid ?

Otherwise I can also suggest another feature: dashboard import/export ? If you think it makes sense, I will create a new issue.

**Comment by dmoll1974** [comment]
I can't think of a use case for a variable-free template...

What you want is probably available in other functions:
- Clone dashboard (under dashboard menu) to clone a dashboard within a product
- Export product (under product menu) to export / import a product

Have you seen those features?

**Comment by loganmzz** [comment]
Cloning isn't the feature I need. Import/Export permits partial backup and migration. However, I haven't seen the product related features. I will take a look at it.

Have you plan to generate a release (branch/tag) ?

**Comment by dmoll1974** [comment]
https://github.com/dmoll1974/targets-io/releases/tag/v1.0.0  :-)

**Comment by loganmzz** [comment]
Fixed
