### ISSUE TITLE
Cancelling or back in history from a metric template goes to variable tab

### ISSUE THREAD

**Issue by loganmzz** [dmoll1974/targets-io#32]
When looking at a metric from a template definition and then trying to go back to the list using "CANCEL" button or web-browser back feature, the first tab is displayed (variable list) not metric list.

FIY it works as expected if we click "SUBMIT" button

**Comment by dmoll1974** [comment]
Fixed:
 [e3024492a46860a55940f20af6f684d9a4b24914](https://github.com/dmoll1974/targets-io/commit/e3024492a46860a55940f20af6f684d9a4b24914)
