### ISSUE TITLE
testRunId don't respect case sensitivity

### ISSUE THREAD

**Issue by loganmzz** [dmoll1974/targets-io#33]
When submitting a new test run, the testRunId is uppercased and targets IO doesn't support insensitive case in URLs. It results in 404 errors when requesting data.

For example, submitting a test run from Jenkins using the `BUILD_TAG` environment variable. The variable is for example `jenkins-MyProject-1` but data in Targets IO is only accessible with JENKINS-MYPROJECT-1.

**Comment by dmoll1974** [comment]
Hi Logan,

For what endpoint do you need the testRunId to be case insensitive? I guess the /benchmarks right?
I have fixed that endpoint, please let me know if you want it for other endpoints too.

[commit/84d775990cbbae241e21c9b07050b89de7cadecd](https://github.com/dmoll1974/targets-io/commit/84d775990cbbae241e21c9b07050b89de7cadecd)

cheers Daniel

**Comment by loganmzz** [comment]
Hi Daniel,

I also use the summary URL route in the error message for Jenkins. Why not just keep input case ?

**Comment by dmoll1974** [comment]
I can't remember why I did this :-) I'll have a look at it...

**Comment by dmoll1974** [comment]
For now I have added case insensitive test run summary endpoint: [7e8c47d7dafdd8fc7779146ebcf970bddf5735af](https://github.com/dmoll1974/targets-io/commit/7e8c47d7dafdd8fc7779146ebcf970bddf5735af)

**Comment by loganmzz** [comment]
It doesn't work for "testrun-summary" as "testrun" resource returns 404

**Comment by dmoll1974** [comment]
which url's exactly are you using?

**Comment by dmoll1974** [comment]
Fixed GUI url's for test run and test run summary: [325479dc69ea66a533b4a02fe6be04b65db26742](https://github.com/dmoll1974/targets-io/commit/325479dc69ea66a533b4a02fe6be04b65db26742)
