### ISSUE TITLE
Test Summary Graphics aren't displayed under Firefox 

### ISSUE THREAD

**Issue by loganmzz** [dmoll1974/targets-io#36]
From Firefox 49.0.2 64-bits portable edition Windows 7, graphics are correctly displayed when viewed from "graphs" page but not from "testrun-summary". Only legend is displayed:
![image](https://cloud.githubusercontent.com/assets/5030510/20136025/2a43591e-a673-11e6-8b40-ba51632c3f49.png)

**Comment by dmoll1974** [comment]
Ok thanks for reporting, I will have a look. General remark:  I use Chrome, so that's the only browser that has been tested.

cheers

Daniel

**Comment by dmoll1974** [comment]
Fixed: [6ee45e8dab4bb7cae312fc86d4caf3c9d3e04e4b](https://github.com/dmoll1974/targets-io/commit/6ee45e8dab4bb7cae312fc86d4caf3c9d3e04e4b)

**Comment by loganmzz** [comment]
To be honest, problem has been reported by project after trying with IE11 ;)
