### ISSUE TITLE
Can't add dashboard from a non-product-related page

### ISSUE THREAD

**Issue by loganmzz** [dmoll1974/targets-io#37]
When viewing a non-product-related page (eg Template), select "Add dashboard" while a product is selected leads to a dashboard creation page without product in route: `http://<root>/#!/add/dashboard//`

**Comment by dmoll1974** [comment]
Thank for reporting!
Fixed it : [afb23dd9e915a194e45a2f6362bcd253f36419ba](https://github.com/dmoll1974/targets-io/commit/afb23dd9e915a194e45a2f6362bcd253f36419ba)
